[package]
name = "game-solver"
description = "Solve any combinatorial game"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LeoDog896/game-solver"
keywords = ["combinatorial-game", "negamax", "minimax", "game-theory"]
categories = ["game", "algorithm"]
version = "0.1.0"
edition = "2021"

[features]
"rayon" = ["dep:rayon", "dep:dashmap"]

[profile.release]
lto = true
panic = "abort"

[dev-dependencies]
anyhow = "1.0.72"
array2d = "0.3.0"
itertools = "0.11.0"
ndarray = "0.15.6"

[dependencies]
dashmap = { version = "5.5.0", optional = true }
rayon = { version = "1.7.0", optional = true }
