[package]
name = "games-cli"
license = "MPL"
edition = "2021"
version = "0.1.0"

[dependencies]
game-solver = { path = "../game-solver", features = ["rayon"] }
games = { path = "../games" }
anyhow = "1.0.86"
clap = { version = "4.5.15", features = ["derive"] }
