[package]
name = "games-cli"
license = "MPL"
edition = "2021"
version = "0.1.0"

[dependencies]
game-solver = { path = "../game-solver", features = ["rayon", "reinforcement"] }
games = { path = "../games" }
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
