[package]
name = "games"
license = "MPL"
edition = "2021"

[dependencies]
game-solver = { path = "../game-solver", features = ["rayon", "reinforcement"] }
anyhow = "1.0.72"
array2d = "0.3.0"
ndarray = "0.15.6"
itertools = "0.13.0"
