name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
    - name: Run Cargo Build
      uses: actions-rs/cargo@v1
      with:
        command: build 
        args: --verbose --examples --all-features
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --examples --all-features
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Check format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Check clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-targets --all-features -- -D warnings
